# Generated by Django 2.1.5 on 2019-02-04 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('circles', '0002_auto_20190204_1537'),
    ]

    operations = [
        migrations.RenameField(
            model_name='membership',
            old_name='remainig_invitation',
            new_name='remaining_invitation',
        ),
    ]
