# Generated by Django 2.1.5 on 2019-02-05 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circles', '0004_auto_20190204_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Only active users are allowed to interact in the circle.', verbose_name='active status'),
        ),
    ]
